import Tabs from '@/components/Tabs'
import './globals.css'
import Footer from '@/components/Footer'
import Link from 'next/link'

export const metadata = {
  title: 'Rick and Morty',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className='h-20 md:h-24 sticky top-0 z-10'>
          <Tabs />
          <Link href="/"><h1 className='font-black text-xl mr-2'>Rick & Morty <span className='text-blue-500'>WIKI</span></h1></Link>
        </header>
        {children}
        <Footer />
      </body>
    </html>
  )
}
